/*
Package macreader changes Classic Mac (CR) line endings to Linux (LF) line
endings in files. This is useful when handling CSV files generated by the Mac
version of Microsoft Excel as documented in this issue:
https://github.com/golang/go/issues/7802.
*/
package macreader

import "io"

var (
	rByte byte = 13 // the byte that corresponds to the '\r' rune.
	nByte byte = 10 // the byte that corresponds to the '\n' rune.
)

type reader struct {
	r io.Reader
}

// New creates a new io.Reader that wraps r to convert Classic Mac (CR)
// line endings to Linux (LF) line endings.
func New(r io.Reader) io.Reader {
	return &reader{r: r}
}

// Read replaces CR line endings in the source reader with LF line endings.
func (r reader) Read(p []byte) (n int, err error) {
	n, err = r.r.Read(p)
	for i, b := range p {
		if b == rByte && i < len(p) && p[i+1] != nByte {
			p[i] = nByte
		}
	}
	return
}
